### ISSUE TITLE
Testovací prostředí - testovací uživatel / osobní údaje

### ISSUE THREAD

**Issue by vaclavpavek** [homecreditcz/oneclick-api#2]
Bylo by dobré vytvořit 2 testovací subjekty (schváleno / zamítnuto) - nyní je pouze "Trener".

Testovací subjekty by měli být kompletní včetně osobních údajů (RČ, číslo OP / dokladu, ...) a to tak aby šlo vždy snadno testovat. Pěkně to má vyřešené GoPay https://help.gopay.com/cs/tema/integrace-platebni-brany/technicky-popis-integrace-platebni-brany/provadeni-plateb-v-testovacim-prostredi

Případně pokud se musí testovat s vlastními údaji tak jak je s mými údaji nakládáno - nechci aby docházelo k lustrování mé osoby ve finančních rejstřících apod. Společnosti Home Credit (vč. spřízněných institucí) nechci dávat žádné své osobní údaje a jakýkoli souhlas.

**Comment by homecreditcz** [comment]
Pro testovací účely není v žádném případě potřeba zadávat reálné údaje. Speciální režim "Trenér" umožní právě to, aby bylo možné procesem v testovacím režimu projít s pseudodaty typu příjmení: Aaa, jméno: Bbb atd.
Na testovacím prostředí nedochází k žádným dotazům do registrů apod. (toto se děje pouze na produkci). Testovací prostředí jsou pravidelně obnovována/přepisována. Zadané údaje jsou v důsledku této obnovy vždy smazány a nahrazeny novou testovací sadou.

**Comment by vaclavpavek** [comment]
Už je to delší dobu, ale myslím, že při druhém testu si systém už určité údaje pamatoval a tudíž průchod byl kratší což je při testování nežádoucí. Navíc není cesta kdy projdu vše validně, ale ze strany HC dojde k zamítnutí... Už to pro mě není aktuální a doufám, že HC už nebudu muset integrovat.
